name: Generate dependency graph for tower-agent
on:
  push:
      branches: ['master']


permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
    - name: Setup Graalvm
      uses: graalvm/setup-graalvm@5298d94fb55a4f185c602eeac5de1b553882abe2 # v1.6.4
      with:
        java-version: '21'
        distribution: 'graalvm-community'
        native-image-musl: 'true'


    - name: Generate and submit dependency graph for tower-agent
      uses: gradle/actions/dependency-submission@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4.4.4
      with:
        dependency-resolution-task: "dependencies"
        additional-arguments: "--configuration runtimeClasspath"
        dependency-graph: generate-and-submit
